### ISSUE TITLE
Whats the COM Object name, for Adobe After Effects Application ?

### ISSUE THREAD

**Issue by samholt** [lohriialo/photoshop-scripting-python#1]
I'm working on a fork of your excellent library for Adobe After Effects full time.

Would you be so kind as to help me connect to the App object of Adobe After Effects ?

Based on your code, you connected to the Photoshop app object via:

```
from win32com.client import Dispatch

app = Dispatch("Photoshop.Application")
```

What would the equivalent Dispatch() be for Adobe After Effects ?

Thank you so much for your time,

Will happily pay for time spent on this,

All the best,
Sam

**Comment by lohriialo** [comment]
AfterEffects and Premier Pro doesn't have COM support so scripting in python via COM is not possible like it's illustrated in [Photoshop ](https://github.com/lohriialo/photoshop-scripting-python)& [InDesign](https://github.com/lohriialo/indesign-scripting-python)

AE's API is in ExtendScript. The best platform from which to select and trigger ExtendScripts (even those driven by Python scripts) is through a CEP (Common Extensibility Platform) panel. 

Here's the 'flagship' panel, that shows what's possible at the JavaScript level: https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_8.x/Samples/CEP_HTML_Test_Extension-8.0

Here's the After Effets panel, basically an empty husk from which to trigger ExtendScript: https://github.com/Adobe-CEP/Samples/tree/master/AfterEffectsPanel

Crowd-sourced scripting API docs for AE: http://docs.aenhancers.com
