### ISSUE TITLE
How to use python to control Photoshop to automatically add jpg images to specified coordinates？

### ISSUE THREAD

**Issue by tangjiahong** [lohriialo/photoshop-scripting-python#11]
Thank you very much for sharing.
    I am a developer of a startup company from China. I have been learning about your shared resources for almost 7 days. Thanks to your sharing, I have solved many problems, but because of my limited ability, I can only understand the sample code you wrote and will not write new functions. There are two problems that I have not solved yet. Please let me know.

1.How to use python to control Photoshop to automatically add jpg images to specified coordinates？
2.How to control Photoshop printing？

If you are convenient, you can email me a reply. Xinrooy.tang@gmail.com
We have seen the projects shared by programmers all over the world. Your sharing is the most valuable. If you need paid help, please come forward.
Thank you for your help.
jiahongtang

**Comment by lohriialo** [comment]
Here's an example on how to place image with actions, hope this helps you get started

``` python
imageFile = r"C:\test\photo1.jpg"
idPlaceImage = app.CharIDToTypeID("Plc ")
placeImageDescriptor = Dispatch('Photoshop.ActionDescriptor')
idnull = app.CharIDToTypeID("null")
placeImageDescriptor.PutPath(idnull, imageFile)
app.ExecuteAction(idPlaceImage, placeImageDescriptor)
```

More examples on how to use actions [EmbossAction.py](https://github.com/lohriialo/photoshop-scripting-python/blob/master/EmbossAction.py), [ExecuteMoltenLead.py](https://github.com/lohriialo/photoshop-scripting-python/blob/master/ExecuteMoltenLead.py) & [ImportDataSetsAction.py](https://github.com/lohriialo/photoshop-scripting-python/blob/master/ImportDataSetsAction.py)
