### ISSUE TITLE
layer.typename is not found?

### ISSUE THREAD

**Issue by siriusi** [lohriialo/photoshop-scripting-python#2]
There is an error: `NameError: Name typename not found` when I run this code:
```
from comtypes.client import GetActiveObject
app = GetActiveObject("Photoshop.Application")
srcDoc = app.Open("E:\\Project\\Page_To_Bar\\images\\MangaTest.psd")
print("type", app.activeDocument.activeLayer.typename)
```
I sure layer.typename is aviliable in ADOBE PHOTOSHOP CC 2015 JAVASCRIPT SCRIPTING REFERENCE
Can you help me?
Thank you.

**Comment by lohriialo** [comment]
typename does exist, instead of comtypes.client, try win32com.client then you should be able to get the typename
