### ISSUE TITLE
Example of setting/getting the active tool? 

### ISSUE THREAD

**Issue by Hyperlooper** [lohriialo/photoshop-scripting-python#6]
Thank you so much for these awesome examples, your repo is the best source of info I have found on using python with Adobe ps. I've been trying to get and set the active Photoshop tool via python and I just don't think I have the syntax quite right because all the examples are in JavaScript. Does anyone happen to have an example of doing this in Python?

**Comment by lohriialo** [comment]
`print(app.CurrentTool) `
gives you the string name of the current selected tool

and to select the tool, set the string name of the tool
`app.CurrentTool = 'cropTool'`
