### ISSUE TITLE
how to set order of layers?

### ISSUE THREAD

**Issue by j421037** [lohriialo/photoshop-scripting-python#9]
I didn't find the relevant API

**Comment by lohriialo** [comment]
See the [ArtLayer](https://github.com/lohriialo/photoshop-scripting-python/blob/master/doc_reference/photoshop_CC_2018.py#L763) class, there's a method [Move()](https://github.com/lohriialo/photoshop-scripting-python/blob/master/doc_reference/photoshop_CC_2018.py#L1046)
